apiVersion: v1
kind: Pod
metadata:
  name: brezyweather-pod
spec:
  containers:
  - image: codewithpraveen/labs-k8s-brezyweather:1.0
    name: brezyweather-pod
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    volumeMounts:
    - name: db-connection-volume
      mountPath: /etc/config
  volumes:
  - name: db-connection-volume
    secret:
      secretName: db-connection-secret
