apiVersion: v1
kind: Secret
metadata:
  name: db-connection-secret
type: Opaque
data:
  username: c2VydmljZQ== # service
  password: UEBzc3cwcmQ= # P@ssw0rd
  host: ZGItc2VydmVyLXN0YWdpbmc= # db-server-staging
  database: YnJlenl3ZWF0aGVy # brezyweather
