apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/brezyweather-deployment.yaml
  - resources/brezyweather-service.yaml
namespace: staging
commonLabels:
  environment: dev
