apiVersion: apps/v1
kind: Deployment
metadata:
  name: brezyweather-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brezyweather
  template:
    metadata:
      labels:
        app: brezyweather
    spec:
      containers:
      - name: brezyweather
        image: codewithpraveen/labs-k8s-brezyweather:1.0
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
        ports:
        - containerPort: 80
